### ISSUE TITLE
No module named 'BaseHTTPServer'

### ISSUE THREAD

**Issue by grzesko01** [rkunze/ft-robo-snap#1]
After trying to run the library I am getting the error. Seems that some changes are needed for Python 3xx

Traceback (most recent call last):
  File "robo-snap.py", line 15, in <module>
    from BaseHTTPServer import HTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'

**Comment by rkunze** [comment]
ft-robo-snap has been superseded by [Brickly](http://cfw.ftcommunity.de/ftcommunity-TXT/de/programming/brickly/) running on the [TXT community firmware](http://cfw.ftcommunity.de/ftcommunity-TXT/de/), so I won't port it forward to Python 3.

If you want to use it nonetheless, feel free to fork and implement the change yourself.
